version: "3.7"

volumes:
  nhm:
    driver: local

services:

  base_image:
    build:
      context: ./base
      labels:
        - "gov.usgs.nhm.image.docker.application=NHM"
        - "gov.usgs.nhm.image.docker.type=Base_Image"
    image: nhmusgs/base
    env_file:
      - nhm.env

  gridmet:
    build:
      context: ./gridmet
      labels:
        - "gov.usgs.nhm.image.docker.application=NHM"
        - "gov.usgs.nhm.image.docker.type=Gridmet_Query"
    image: nhmusgs/gridmet:0.30
    container_name: gridmet
    env_file:
      - nhm.env

  gridmetetl:
    build:
      context: ./gridmetetl
      labels:
        - "gov.usgs.nhm.image.docker.application=NHM"
        - "gov.usgs.nhm.image.docker.type=GRIDMET_ETL"
    image: nhmusgs/gridmetetl:0.30
    container_name: gridmetetl
    environment:
      - CBH_IDIR
      - START_DATE
      - END_DATE
      - NHM_SOURCE_DIR
    env_file:
      - nhm.env
    volumes:
      - nhm:/nhm

  gridmets2s:
    build:
      context: ./gridmets2s
      labels:
        - "gov.usgs.nhm.image.docker.application=NHM"
        - "gov.usgs.nhm.image.docker.type=GRIDMETETL_S2S"
    image: nhmusgs/gridmets2s:0.2.1
    container_name: gridmets2s
    environment:
      - S2S_GMTYPE
      - S2S_MODELSHAPE
      - S2S_MODELWGHTS
      - S2S_OPATH
      - S2S_ELEVFILE
      - S2S_INTERPTYPE
      - S2S_DATE
    env_file:
      - nhm.env
    volumes:
      - nhm:/nhm

  ncf2cbh:
    build:
      context: ./ncf2cbh
      labels:
        - "gov.usgs.nhm.image.docker.application=NHM"
        - "gov.usgs.nhm.image.docker.type=NCF2CBH"
    image: nhmusgs/ncf2cbh:0.2.0
    container_name: ncf2cbh
    environment:
      - NCF_IDIR
      - NCF_DATE
      - NCF_PREFIX
    env_file:
      - nhm.env
    volumes:
      - nhm:/nhm

  cbhfiller:
    build:
      context: ./cbhfiller
      labels:
        - "gov.usgs.nhm.image.docker.application=NHM"
        - "gov.usgs.nhm.image.docker.type=CBHFILLER"
    image: nhmusgs/cbhfiller:0.2.0
    container_name: cbhfiller
    environment:
        - CBH_IDIR
        - CBH_ODIR
    env_file:
      - nhm.env
    volumes:
      - nhm:/nhm

  nhm-prms:
    build:
      context: ./prms
      labels:
        - "gov.usgs.nhm.image.docker.application=NHM"
        - "gov.usgs.nhm.image.docker.type=PRMS"
    image: nhmusgs/nhm-prms:5.2.1
    container_name: nhm-prms
    environment:
      - NHM_SOURCE_DIR
      - PRMS_CONTROL_FILE
      - PRMS_END_TIME
      - PRMS_INIT_VARS_FROM_FILE
      - PRMS_RESTART_DATE
      - PRMS_RUN_TYPE
      - PRMS_SAVE_VARS_TO_FILE
      - PRMS_START_TIME
      - PRMS_VAR_INIT_FILE
      - PRMS_VAR_SAVE_FILE
      - RESTART_DATE
      - START_DATE
    env_file:
      - nhm.env
    volumes:
      - nhm:/nhm

  out2ncf:
    build:
      context: ./out2ncf
      labels:
        - "gov.usgs.nhm.image.docker.application=NHM"
        - "gov.usgs.nhm.image.docker.type=OUT2NCF"
    image: nhmusgs/out2ncf:0.2.0
    container_name: out2ncf
    environment:
      - OUT_NCF_DIR
    env_file:
      - nhm.env
    volumes:
      - nhm:/nhm

  verifier:
    build:
      context: ./verifier
      labels:
        - "gov.usgs.nhm.image.docker.application=NHM"
        - "gov.usgs.nhm.image.docker.type=Verifier"
    image: nhmusgs/verifier:0.1.1
    container_name: verifier
    env_file:
      - nhm.env
    volumes:
      - nhm:/nhm
    command:
      - "/nhm/NHM_PRMS_CONUS_GF_1_1/"
