version: 1
disable_existing_loggers: False
formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  rotating_file: 
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: pyonhm.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
loggers:
  pyonhm:
    handlers: [console, rotating_file]
    level: INFO
    propagate: no
root:
  handlers: [console, rotating_file]
  level: INFO
